### PR TITLE
Feat/configure cluster endpoint

### PR DESCRIPTION
**Pull request by fulv0us**
# PR Description

There are no variables to configure public and private access to the eks cluster endpoint.
It is not possible to restrict access to the eks endpoint to only the vpn server.
There is no variable to set the IP address that will have access to the web console.

## Type of change

- [x] New variable pritunl_vpn_access_cidr_blocks
- [x] New variable eks_cluster_endpoint_only_pritunl
- [x] New variable eks_cluster_endpoint_public_access
- [x] New variable eks_cluster_endpoint_private_access
- [x] Documentation update

# Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by halfb00t — APPROVED** [review]
@fulv0us Thank you for your changes. Looks great!

**Comment by halfb00t** [comment]
@fulv0us Could you plz push formatted `aws-eks.tf`?
https://github.com/maddevsio/aws-eks-base/runs/5182345124?check_suite_focus=true#step:4:26

**Comment by fulv0us** [comment]
> @fulv0us Could you plz push formatted `aws-eks.tf`? https://github.com/maddevsio/aws-eks-base/runs/5182345124?check_suite_focus=true#step:4:26

okay

**Comment by fulv0us** [comment]
> @fulv0us Could you plz push formatted `aws-eks.tf`? https://github.com/maddevsio/aws-eks-base/runs/5182345124?check_suite_focus=true#step:4:26

ready

**Pull request merged**
