### PR TITLE
Set helm releases history size.

### PR DESCRIPTION
**Pull request by mglotov**
Helm keeps releases history as k8s secrets. If we don't set max_history it will be unlimited.
There is an opened issue related to that https://github.com/helm/helm/issues/7997.
If count of secrets is huge then helm list/istall can be failed due to:
```
request.go:924] Unexpected error when reading response body: net/http: request canceled (Client.Timeout exceeded while reading body)
Error: unable to build kubernetes objects from release manifest: unexpected error when reading response body. Please retry. Original error: net/http: request canceled (Client.Timeout exceeded while reading body
```

### CODE REVIEW

**Comment by halfb00t** [comment]
@mglotov wouldn't it better to set this limit using variable?

**Comment by mglotov** [comment]
> @mglotov wouldn't it better to set this limit using variable?

**Comment by mglotov** [comment]
@halfb00t Do you want to set them as we do for helm chart version?

**Comment by halfb00t** [comment]
> @halfb00t Do you want to set them as we do for helm chart version?

@mglotov i think single var for all system releases is enough =)

**Comment by mglotov** [comment]
@p1gmale0n hmm, is it really OK to have one variable for all releases?

**Comment by p1gmale0n** [comment]
> @p1gmale0n hmm, is it really OK to have one variable for all releases?

i think this is ok for as the default behavior.
you can still change the specific value for a specific release, if necessary

**Comment by arthur-c** [comment]
Does it cover failed releases?

In https://github.com/helm/helm/issues/7997#issuecomment-825793882 we ended with lots of release versions due to a deployment bug that went for few weeks. We had a loop deploying helm releases that always failed (failure unrelated to helm), then retried... So we had thousands of failed versions.

**Review by p1gmale0n — APPROVED** [review]

**Review by halfb00t — APPROVED** [review]

**Comment by mglotov** [comment]
> Does it cover failed releases?
> 
> In [helm/helm#7997 (comment)](https://github.com/helm/helm/issues/7997#issuecomment-825793882) we ended with lots of release versions due to a deployment bug that went for few weeks. We had a loop deploying helm releases that always failed (failure unrelated to helm), then retried... So we had thousands of failed versions.

Yes, it does. It covers all release versions (failed, deployed, ..). There are some changes in helm v3.5.3 and terraform-helm-provider v2.1.1. Starting from those if you don't have at least one deployed release, then you are limited by max_history size and can't deploy any new release version, even if it's a working release version. You will need to increase max_history value or delete a k8s secret with the release version.

**Pull request merged**
